version: "3.8"

services:
  ex-streamlit:
    build:
      context: ./
      target: streamlit
      dockerfile: Dockerfile
    restart: unless-stopped
    command: [ "streamlit", "run", "streamlit_app.py" ]
    volumes:
      - ./src:/home/app
    ports:
      - "8501:8501"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
  ex-lab:
    build:
      context: ./
      target: jupyter
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      JUPYTER_CONFIG_DIR: "/home/app/.jupyterlab"
      JUPYTERHUB_DIR: "/home/app/notebooks"
      JUPYTER_PORT: 8888
    command: [ "jupyter", "lab", "--ip=*", "--no-browser", "--allow-root" ]
    volumes:
      - ./.jupyterlab:/home/app/.jupyterlab
      - ./src:/home/app/src/
      - ./notebooks:/home/app/notebooks/
      - ./notebooks/.ipynb_checkpoints:/home/app/notebooks/.ipynb_checkpoints
      - ./notebooks/.ipython:/home/app/notebooks/.ipython
      - ./notebooks/.local:/home/app/notebooks/.local
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
